PS C:\IoT-Kafka-Project> cd producer
PS C:\IoT-Kafka-Project\producer> python iot_producer.py
Starting IoT Producer...
Sent: {'machine_id': 3, 'temperature': 51.94, 'vibration': 3.49, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 73.25, 'vibration': 1.5, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 51.24, 'vibration': 2.34, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 23.53, 'vibration': 3.09, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 65.96, 'vibration': 0.52, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 30.82, 'vibration': 2.66, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 32.37, 'vibration': 0.51, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 91.9, 'vibration': 3.86, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 34.07, 'vibration': 4.6, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 50.56, 'vibration': 2.09, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 80.65, 'vibration': 4.95, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 65.39, 'vibration': 3.27, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 60.28, 'vibration': 0.41, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 64.7, 'vibration': 4.52, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 23.02, 'vibration': 0.63, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 46.49, 'vibration': 0.16, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 79.08, 'vibration': 0.43, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 26.76, 'vibration': 2.02, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 98.53, 'vibration': 2.73, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 34.29, 'vibration': 1.02, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 48.57, 'vibration': 3.76, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 49.22, 'vibration': 1.66, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 82.68, 'vibration': 2.14, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 99.27, 'vibration': 3.68, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 83.52, 'vibration': 2.76, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 81.21, 'vibration': 4.6, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 69.81, 'vibration': 1.54, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 56.99, 'vibration': 3.19, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 47.36, 'vibration': 1.44, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 42.41, 'vibration': 1.08, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 74.52, 'vibration': 0.44, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 79.61, 'vibration': 3.91, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 58.74, 'vibration': 2.94, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 21.06, 'vibration': 0.24, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 83.04, 'vibration': 3.99, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 70.69, 'vibration': 1.64, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 91.94, 'vibration': 0.5, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 58.53, 'vibration': 3.53, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 88.17, 'vibration': 4.01, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 46.97, 'vibration': 0.89, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 51.37, 'vibration': 3.58, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 58.33, 'vibration': 4.29, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 49.66, 'vibration': 0.72, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 22.19, 'vibration': 2.29, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 64.83, 'vibration': 3.41, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 41.36, 'vibration': 0.45, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 72.24, 'vibration': 2.02, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 29.28, 'vibration': 2.19, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 96.17, 'vibration': 1.86, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 32.89, 'vibration': 0.56, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 57.25, 'vibration': 0.63, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 64.05, 'vibration': 2.86, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 23.28, 'vibration': 3.66, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 38.32, 'vibration': 4.12, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 22.61, 'vibration': 2.06, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 20.69, 'vibration': 3.47, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 63.86, 'vibration': 2.29, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 26.13, 'vibration': 4.24, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 39.73, 'vibration': 1.01, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 69.51, 'vibration': 1.63, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 88.83, 'vibration': 2.84, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 80.62, 'vibration': 0.94, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 65.26, 'vibration': 1.97, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 64.52, 'vibration': 4.32, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 47.33, 'vibration': 3.85, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 42.28, 'vibration': 1.46, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 81.51, 'vibration': 3.27, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 76.82, 'vibration': 0.87, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 46.56, 'vibration': 0.96, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 80.71, 'vibration': 2.44, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 32.36, 'vibration': 3.81, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 56.02, 'vibration': 4.55, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 51.75, 'vibration': 1.65, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 50.08, 'vibration': 3.16, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 79.46, 'vibration': 1.92, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 38.06, 'vibration': 2.1, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 44.45, 'vibration': 4.43, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 62.62, 'vibration': 2.51, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 94.07, 'vibration': 2.64, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 35.34, 'vibration': 2.06, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 74.0, 'vibration': 1.14, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 45.96, 'vibration': 3.6, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 98.13, 'vibration': 1.35, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 45.57, 'vibration': 2.92, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 81.89, 'vibration': 1.23, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 90.41, 'vibration': 3.46, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 82.53, 'vibration': 3.08, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 70.0, 'vibration': 3.21, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 24.33, 'vibration': 3.54, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 47.19, 'vibration': 2.03, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 76.76, 'vibration': 4.8, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 98.31, 'vibration': 4.78, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 52.9, 'vibration': 0.57, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 97.07, 'vibration': 2.89, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 40.74, 'vibration': 2.76, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 87.12, 'vibration': 3.13, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 68.81, 'vibration': 4.44, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 69.08, 'vibration': 1.07, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 74.75, 'vibration': 2.16, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 58.33, 'vibration': 4.34, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 57.97, 'vibration': 3.52, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 98.28, 'vibration': 4.0, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 61.64, 'vibration': 0.81, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 43.52, 'vibration': 1.24, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 57.9, 'vibration': 2.16, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 47.06, 'vibration': 0.98, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 20.46, 'vibration': 0.8, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 98.13, 'vibration': 0.92, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 53.06, 'vibration': 4.12, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 28.56, 'vibration': 1.04, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 26.49, 'vibration': 2.78, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 26.7, 'vibration': 0.97, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 36.15, 'vibration': 4.43, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 95.32, 'vibration': 3.64, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 82.31, 'vibration': 4.64, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 46.46, 'vibration': 2.1, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 31.32, 'vibration': 2.82, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 26.23, 'vibration': 0.4, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 68.43, 'vibration': 4.38, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 44.31, 'vibration': 2.1, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 45.32, 'vibration': 4.17, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 90.57, 'vibration': 4.79, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 78.84, 'vibration': 3.54, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 40.45, 'vibration': 2.21, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 64.65, 'vibration': 5.0, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 60.07, 'vibration': 3.79, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 98.45, 'vibration': 0.96, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 63.27, 'vibration': 4.98, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 66.44, 'vibration': 3.7, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 36.02, 'vibration': 0.69, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 54.48, 'vibration': 1.11, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 79.25, 'vibration': 1.85, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 78.2, 'vibration': 4.5, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 41.2, 'vibration': 3.48, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 93.52, 'vibration': 1.57, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 28.11, 'vibration': 3.15, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 38.28, 'vibration': 3.54, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 43.11, 'vibration': 4.53, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 71.69, 'vibration': 2.14, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 33.44, 'vibration': 2.08, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 74.94, 'vibration': 0.85, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 88.21, 'vibration': 4.46, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 30.59, 'vibration': 0.2, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 68.43, 'vibration': 0.67, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 26.09, 'vibration': 0.61, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 71.17, 'vibration': 0.84, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 26.69, 'vibration': 2.01, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 85.52, 'vibration': 1.58, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 31.58, 'vibration': 3.07, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 63.66, 'vibration': 0.99, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 32.69, 'vibration': 4.67, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 33.03, 'vibration': 3.64, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 38.53, 'vibration': 1.1, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 99.92, 'vibration': 1.81, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 25.76, 'vibration': 1.06, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 39.12, 'vibration': 4.25, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 68.92, 'vibration': 3.7, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 96.35, 'vibration': 4.18, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 83.06, 'vibration': 3.16, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 80.8, 'vibration': 1.49, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 93.43, 'vibration': 0.64, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 79.2, 'vibration': 0.57, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 52.66, 'vibration': 2.7, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 93.58, 'vibration': 4.32, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 32.51, 'vibration': 4.94, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 74.5, 'vibration': 2.65, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 61.71, 'vibration': 1.87, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 71.93, 'vibration': 1.96, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 71.15, 'vibration': 1.79, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 31.4, 'vibration': 3.84, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 30.1, 'vibration': 3.28, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 62.17, 'vibration': 3.4, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 45.76, 'vibration': 2.85, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 55.85, 'vibration': 3.93, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 22.84, 'vibration': 1.63, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 42.27, 'vibration': 3.92, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 87.52, 'vibration': 3.5, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 58.18, 'vibration': 0.21, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 78.21, 'vibration': 2.28, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 74.25, 'vibration': 4.18, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 43.9, 'vibration': 4.15, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 49.49, 'vibration': 1.1, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 60.04, 'vibration': 0.24, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 74.48, 'vibration': 0.46, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 57.2, 'vibration': 0.9, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 25.52, 'vibration': 3.54, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 76.01, 'vibration': 0.86, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 61.6, 'vibration': 1.04, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 23.86, 'vibration': 4.34, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 91.61, 'vibration': 4.12, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 80.21, 'vibration': 2.91, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 97.35, 'vibration': 2.4, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 76.86, 'vibration': 2.25, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 89.14, 'vibration': 4.8, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 76.24, 'vibration': 4.11, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 36.72, 'vibration': 3.09, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 29.62, 'vibration': 2.97, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 31.08, 'vibration': 4.63, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 75.32, 'vibration': 1.89, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 59.66, 'vibration': 1.28, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 74.42, 'vibration': 0.61, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 93.26, 'vibration': 1.47, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 71.06, 'vibration': 1.56, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 57.93, 'vibration': 2.28, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 49.73, 'vibration': 3.59, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 60.68, 'vibration': 1.78, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 48.84, 'vibration': 3.04, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 32.12, 'vibration': 2.59, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 37.57, 'vibration': 2.74, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 49.06, 'vibration': 1.69, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 85.88, 'vibration': 3.45, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 83.94, 'vibration': 0.46, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 51.84, 'vibration': 1.74, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 84.04, 'vibration': 1.26, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 73.23, 'vibration': 3.11, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 45.63, 'vibration': 1.35, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 55.99, 'vibration': 2.38, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 61.81, 'vibration': 3.41, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 52.1, 'vibration': 2.28, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 95.23, 'vibration': 0.96, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 75.22, 'vibration': 3.14, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 48.87, 'vibration': 2.7, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 78.13, 'vibration': 0.88, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 50.79, 'vibration': 1.37, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 95.62, 'vibration': 1.79, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 92.47, 'vibration': 2.39, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 84.31, 'vibration': 2.72, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 76.13, 'vibration': 4.5, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 63.12, 'vibration': 4.35, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 45.21, 'vibration': 4.61, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 42.23, 'vibration': 0.1, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 54.57, 'vibration': 2.96, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 22.02, 'vibration': 3.78, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 99.23, 'vibration': 2.76, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 44.06, 'vibration': 0.28, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 87.26, 'vibration': 1.74, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 26.54, 'vibration': 3.51, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 58.48, 'vibration': 1.47, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 38.69, 'vibration': 4.84, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 65.91, 'vibration': 3.27, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 37.6, 'vibration': 3.29, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 84.61, 'vibration': 1.02, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 37.98, 'vibration': 1.25, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 90.2, 'vibration': 3.27, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 55.28, 'vibration': 4.9, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 68.15, 'vibration': 1.12, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 40.92, 'vibration': 2.67, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 87.38, 'vibration': 4.26, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 55.99, 'vibration': 4.16, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 89.95, 'vibration': 3.27, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 49.33, 'vibration': 3.14, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 96.37, 'vibration': 4.54, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 94.21, 'vibration': 4.61, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 43.67, 'vibration': 0.21, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 36.7, 'vibration': 2.65, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 38.25, 'vibration': 1.35, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 78.67, 'vibration': 4.91, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 38.83, 'vibration': 4.43, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 38.45, 'vibration': 2.07, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 49.73, 'vibration': 2.38, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 65.54, 'vibration': 3.95, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 27.29, 'vibration': 1.23, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 46.12, 'vibration': 0.23, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 97.0, 'vibration': 3.21, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 36.09, 'vibration': 2.59, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 34.77, 'vibration': 2.68, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 24.23, 'vibration': 1.23, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 74.71, 'vibration': 1.59, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 29.32, 'vibration': 4.9, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 65.36, 'vibration': 4.3, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 54.75, 'vibration': 0.61, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 42.15, 'vibration': 4.79, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 83.07, 'vibration': 0.58, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 67.96, 'vibration': 1.66, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 24.36, 'vibration': 0.58, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 67.24, 'vibration': 3.38, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 98.95, 'vibration': 4.13, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 85.74, 'vibration': 1.75, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 55.18, 'vibration': 4.88, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 80.9, 'vibration': 2.91, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 90.53, 'vibration': 4.6, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 75.94, 'vibration': 0.15, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 79.64, 'vibration': 4.9, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 78.35, 'vibration': 4.84, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 92.74, 'vibration': 2.28, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 60.07, 'vibration': 0.58, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 47.52, 'vibration': 1.98, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 71.8, 'vibration': 4.34, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 64.05, 'vibration': 1.15, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 80.87, 'vibration': 0.14, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 28.21, 'vibration': 4.67, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 99.24, 'vibration': 1.9, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 59.3, 'vibration': 2.7, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 24.87, 'vibration': 4.26, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 20.23, 'vibration': 3.38, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 78.94, 'vibration': 2.58, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 89.24, 'vibration': 3.97, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 98.23, 'vibration': 3.19, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 70.26, 'vibration': 2.32, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 89.5, 'vibration': 0.89, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 94.87, 'vibration': 0.45, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 66.75, 'vibration': 1.91, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 90.93, 'vibration': 4.68, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 82.98, 'vibration': 1.67, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 60.64, 'vibration': 3.83, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 37.28, 'vibration': 4.59, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 33.39, 'vibration': 1.9, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 36.34, 'vibration': 1.88, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 64.92, 'vibration': 4.15, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 29.88, 'vibration': 2.65, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 20.53, 'vibration': 2.82, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 67.08, 'vibration': 1.58, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 39.33, 'vibration': 2.13, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 71.05, 'vibration': 4.68, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 96.37, 'vibration': 2.31, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 56.45, 'vibration': 1.16, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 34.99, 'vibration': 0.99, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 41.79, 'vibration': 2.02, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 24.78, 'vibration': 2.59, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 37.52, 'vibration': 2.87, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 84.99, 'vibration': 0.6, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 82.5, 'vibration': 1.48, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 57.57, 'vibration': 3.08, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 50.07, 'vibration': 0.93, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 49.41, 'vibration': 3.58, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 25.39, 'vibration': 3.94, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 31.07, 'vibration': 2.56, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 95.5, 'vibration': 2.37, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 89.22, 'vibration': 0.41, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 51.19, 'vibration': 1.34, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 50.5, 'vibration': 4.33, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 81.03, 'vibration': 1.8, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 78.42, 'vibration': 4.87, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 89.22, 'vibration': 1.83, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 28.18, 'vibration': 0.88, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 57.25, 'vibration': 0.87, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 24.29, 'vibration': 4.16, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 40.19, 'vibration': 4.81, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 86.36, 'vibration': 4.12, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 57.06, 'vibration': 0.51, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 73.44, 'vibration': 1.9, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 91.66, 'vibration': 1.0, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 91.49, 'vibration': 4.63, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 99.56, 'vibration': 0.11, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 80.05, 'vibration': 2.94, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 93.17, 'vibration': 0.6, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 66.47, 'vibration': 3.53, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 95.49, 'vibration': 0.79, 'status': 'RUNNING'}
Sent: {'machine_id': 3, 'temperature': 72.64, 'vibration': 1.56, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 94.45, 'vibration': 4.4, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 84.96, 'vibration': 1.56, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 46.89, 'vibration': 4.37, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 33.13, 'vibration': 0.64, 'status': 'RUNNING'}
Sent: {'machine_id': 1, 'temperature': 32.06, 'vibration': 0.42, 'status': 'RUNNING'}
Sent: {'machine_id': 4, 'temperature': 79.24, 'vibration': 3.15, 'status': 'RUNNING'}
Sent: {'machine_id': 5, 'temperature': 61.09, 'vibration': 3.08, 'status': 'RUNNING'}
Sent: {'machine_id': 2, 'temperature': 37.42, 'vibration': 2.6, 'status': 'RUNNING'}